trigger: none

pool:
  vmImage: 'ubuntu-latest'


parameters:
  - name: deployToDev
    type: boolean
    default: true
  - name: deployToTest
    type: boolean
    default: false
  - name: deployToProd
    type: boolean
    default: false
  - name: ServiceConnectionName
    type: string
    default: 'Azure-Sven'
  - name: Location
    default: westeurope

 
stages:
  - stage: Build
    displayName: 'Build Resources'
    
    jobs:
    - template: deploy/functionApp/build-function-app.yml
      parameters:
        csprojFilePath: '$(System.DefaultWorkingDirectory)/src/functionAppReceiver/functionApp.csproj'

      

  - stage: Dev
    condition: and( eq('${{ parameters.deployToDev }}','true'), succeeded('Build') )
    dependsOn: Build  
    displayName: 'Deploy to Dev'
    jobs: 
    - template: 'deploy/infrastructure/deploy-infrastructure-skip.yml'
      parameters: 
        environment: 'Dev'
    - template: 'deploy/functionApp/deploy-function-app.yml'
      parameters: 
        environment: 'Dev'
        serviceConnectionName: '${{ parameters.ServiceConnectionName }}'
        funcAppName: 'fa-dwxdemo5-integration-receiver-dev'

  
  #- stage: Test
  #  condition: and( eq('${{ parameters.deployToTest }}','true'), succeeded('Dev') )
  #  dependsOn: Dev  
  #  displayName: 'Deploy to Test'
  #  jobs: 
 
 

 # - stage: Prod
 #   condition: and( eq('${{ parameters.deployToProd }}','true'), succeeded('Test') )
 #   dependsOn: Test  
 #   displayName: 'Deploy to Prod'
  #  jobs: 
