parameters:
  - name: csprojFilePath

jobs:
  - job: BuildFunctionApp
    displayName: "Build Azure Function"
    steps:
      - task: UseDotNet@2
        displayName: Use .NET Core
        inputs:
          packageType: "sdk"
          version: "9.x"

      - task: DotNetCoreCLI@2
        displayName: Restore nuget
        inputs:
          command: 'restore'
          projects: ${{ parameters.csprojFilePath }}
        
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: ${{ parameters.csprojFilePath }}
      
      - task: DotNetCoreCLI@2
        displayName: Build Functions
        inputs:
          command: "publish"
          publishWebProjects: false
          projects: ${{ parameters.csprojFilePath }}
          arguments: "--configuration Release --output $(Build.ArtifactStagingDirectory)"
      - publish: "$(Build.ArtifactStagingDirectory)"
        displayName: "Publish zip"
        artifact: dropFunctionApp